index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'home/index.html.twig'

register:
  path: /register
  controller: App\Controller\UserController::register
  defaults:
    template: 'home/index.html.twig'

home:
   path: /home
   controller: App\Controller\DefaultController::home

loginGet:
  path: /login
  controller: App\Controller\UserController::getLogin
  methods: GET

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: POST